name=eva-core
version=1.0.0
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=Event-driven library for Arduino
paragraph=Provides event-driven style of coding. Highly adjustable hierarhial structure for Button, MultiButton, Timer, Indicator and more
category=Arhitecture
url=https://github.com/yourname/EvaLibrary
architectures=*
includes=evaTac.h

